Fixed build error on Visual Studio 2010/2012.
Due to incomplete support of Variadic Templates of C++ 11 in Visual Studio 2010/2012,
a preprocessor should be defined: _VARIADIC_MAX=10

Build error looks like below:
  error C2977: 'std::tuple' : too many template arguments

Stack Overflow link: http://bit.ly/1cP592z